#############################################################################
# Makefile for building: QPaper
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Feb 9 20:13:42 2015
# Project:  QPaper.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QPaper.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		newproject.cpp \
		projectdata.cpp \
		newpaper.cpp \
		paperdata.cpp \
		journals.cpp \
		addjournal.cpp moc_mainwindow.cpp \
		moc_newproject.cpp \
		moc_newpaper.cpp \
		moc_journals.cpp \
		moc_addjournal.cpp \
		qrc_qpaperres.cpp
OBJECTS       = main.o \
		mainwindow.o \
		newproject.o \
		projectdata.o \
		newpaper.o \
		paperdata.o \
		journals.o \
		addjournal.o \
		moc_mainwindow.o \
		moc_newproject.o \
		moc_newpaper.o \
		moc_journals.o \
		moc_addjournal.o \
		qrc_qpaperres.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QPaper.pro
QMAKE_TARGET  = QPaper
DESTDIR       = 
TARGET        = QPaper

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_newproject.h ui_newpaper.h ui_journals.h ui_addjournal.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QPaper.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QPaper.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QPaper.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QPaper1.0.0 || $(MKDIR) .tmp/QPaper1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QPaper1.0.0/ && $(COPY_FILE) --parents mainwindow.h newproject.h projectdata.h newpaper.h paperdata.h journals.h addjournal.h .tmp/QPaper1.0.0/ && $(COPY_FILE) --parents qpaperres.qrc .tmp/QPaper1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp newproject.cpp projectdata.cpp newpaper.cpp paperdata.cpp journals.cpp addjournal.cpp .tmp/QPaper1.0.0/ && $(COPY_FILE) --parents mainwindow.ui newproject.ui newpaper.ui journals.ui addjournal.ui .tmp/QPaper1.0.0/ && (cd `dirname .tmp/QPaper1.0.0` && $(TAR) QPaper1.0.0.tar QPaper1.0.0 && $(COMPRESS) QPaper1.0.0.tar) && $(MOVE) `dirname .tmp/QPaper1.0.0`/QPaper1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QPaper1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_newproject.cpp moc_newpaper.cpp moc_journals.cpp moc_addjournal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_newproject.cpp moc_newpaper.cpp moc_journals.cpp moc_addjournal.cpp
moc_mainwindow.cpp: newproject.h \
		newpaper.h \
		journals.h \
		addjournal.h \
		projectdata.h \
		mainwindow.h \
		paperdata.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_newproject.cpp: newproject.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) newproject.h -o moc_newproject.cpp

moc_newpaper.cpp: journals.h \
		addjournal.h \
		newpaper.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) newpaper.h -o moc_newpaper.cpp

moc_journals.cpp: addjournal.h \
		journals.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) journals.h -o moc_journals.cpp

moc_addjournal.cpp: addjournal.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) addjournal.h -o moc_addjournal.cpp

compiler_rcc_make_all: qrc_qpaperres.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qpaperres.cpp
qrc_qpaperres.cpp: qpaperres.qrc \
		Journal_strings.txt
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name qpaperres qpaperres.qrc -o qrc_qpaperres.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_newproject.h ui_newpaper.h ui_journals.h ui_addjournal.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_newproject.h ui_newpaper.h ui_journals.h ui_addjournal.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_newproject.h: newproject.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic newproject.ui -o ui_newproject.h

ui_newpaper.h: newpaper.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic newpaper.ui -o ui_newpaper.h

ui_journals.h: journals.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic journals.ui -o ui_journals.h

ui_addjournal.h: addjournal.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic addjournal.ui -o ui_addjournal.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		newproject.h \
		newpaper.h \
		journals.h \
		addjournal.h \
		projectdata.h \
		paperdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		newproject.h \
		newpaper.h \
		journals.h \
		addjournal.h \
		projectdata.h \
		paperdata.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

newproject.o: newproject.cpp newproject.h \
		ui_newproject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newproject.o newproject.cpp

projectdata.o: projectdata.cpp projectdata.h \
		mainwindow.h \
		newproject.h \
		newpaper.h \
		journals.h \
		addjournal.h \
		paperdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectdata.o projectdata.cpp

newpaper.o: newpaper.cpp newpaper.h \
		journals.h \
		addjournal.h \
		ui_newpaper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newpaper.o newpaper.cpp

paperdata.o: paperdata.cpp paperdata.h \
		mainwindow.h \
		newproject.h \
		newpaper.h \
		journals.h \
		addjournal.h \
		projectdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paperdata.o paperdata.cpp

journals.o: journals.cpp journals.h \
		addjournal.h \
		ui_journals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o journals.o journals.cpp

addjournal.o: addjournal.cpp addjournal.h \
		ui_addjournal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addjournal.o addjournal.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_newproject.o: moc_newproject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newproject.o moc_newproject.cpp

moc_newpaper.o: moc_newpaper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newpaper.o moc_newpaper.cpp

moc_journals.o: moc_journals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_journals.o moc_journals.cpp

moc_addjournal.o: moc_addjournal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addjournal.o moc_addjournal.cpp

qrc_qpaperres.o: qrc_qpaperres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qpaperres.o qrc_qpaperres.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

